---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	route(route)
	disambig_init(disambig_init)
	plan(plan)
	skeleton(skeleton)
	fill_methods(fill_methods)
	compile(compile)
	test(test)
	schema_learn(schema_learn)
	patch(patch)
	done(done)
	__end__([<p>__end__</p>]):::last
	__start__ --> route;
	compile -.-> done;
	compile -.-> patch;
	compile -.-> test;
	disambig_init --> plan;
	fill_methods --> compile;
	patch -.-> compile;
	plan --> skeleton;
	route -.-> disambig_init;
	route -.-> patch;
	schema_learn -.-> done;
	schema_learn -.-> patch;
	skeleton --> fill_methods;
	test -.-> schema_learn;
	done --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
